name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/ci.yaml

  publish:
    name: Publish release assets
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.ref_name }}
      MESSAGE: "WIP"
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: hetzner-k3s-*
          merge-multiple: true

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ env.GITHUB_TOKEN }}
          file: hetzner-k3s-*
          file_glob: true
          tag: ${{ env.VERSION }}
          overwrite: true
          body: ${{ env.MESSAGE }}
